# Generated by Django 4.2.1 on 2023-05-21 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=100)),
                ('english_translation', models.CharField(max_length=100)),
                ('danish_translation', models.CharField(max_length=100)),
                ('eu', models.CharField(max_length=100)),
                ('voce_ele_ela', models.CharField(max_length=100)),
                ('nos', models.CharField(max_length=100)),
                ('voces_eles_elas', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verb.verbcategory')),
            ],
        ),
    ]
