# Generated by Django 4.2.1 on 2023-05-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
