# Generated by Django 4.2.1 on 2023-05-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verb', '0002_verb_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verb',
            name='audio',
        ),
        migrations.CreateModel(
            name='VerbAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='verb_audio')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verb.verb')),
            ],
        ),
    ]
